App\Entity\Client:
  attributes:
    normalization_context:
      groups: ['client_read']

    denormalization_context:
      groups: ['client_write']

  collectionOperations:
    get:
      method: 'GET'
      security: 'is_granted("ROLE_READ_CLIENT") or is_granted("ROLE_GOD")'

    post:
      menthod: 'POST'
      security: 'is_granted("ROLE_CREATE_CLIENT") or is_granted("ROLE_GOD")'

  itemOperations:
    get:
      method: 'GET'
      security: 'is_granted("CREATED", object)'

    put:
      method: 'PUT'
      security: 'is_granted("EDITED", object)'

    delete:
      method: 'DELETE'
      security: 'is_granted("DELETE", object)'