App\Entity\User:
  attributes:
    normalization_context:
      groups: ['user_read']

    denormalization_context:
      groups: ['user_write']

  collectionOperations:
    get:
      method: 'GET'
      security: 'is_granted("ROLE_READ_USER") or is_granted("ROLE_GOD") or is_granted("ROLE_ADMIN")'

    post:
      menthod: 'POST'
      security: 'is_granted("ROLE_CREATE_USER") or is_granted("ROLE_GOD") or is_granted("ROLE_ADMIN")'

  itemOperations:
    get:
      method: 'GET'
      security: 'is_granted("CREATE", object)'

    put:
      method: 'PUT'
      security: 'is_granted("UPDATE", object)'
      swagger_context:
        parameters:
          - in: body
            name: user
            description: The user to update
            schema:
              type: object
              required:
                - name
                - email
                - roles
              properties:
                name:
                  type: string
                email:
                  type: string
                roles:
                  type: array
                  items:
                    type: string
    delete:
      method: 'DELETE'
      security: 'is_granted("DELETE", object)'