App\Entity\Category:
  attributes:
    id:
      groups: ['category_read']
    name:
      groups: ['category_read', 'category_write','product_read']

    description:
      groups: ['category_read', 'category_write']

    user:
      groups: ['category_read', 'category_write']

    company:
      groups: ['category_read', 'category_write']

    createdAt:
      groups: ['category_read']

    updatedAt:
      groups: ['category_read']