App\Entity\Company:
  attributes:
    id:
      groups: ['company_read']

    name:
      groups: ['company_read', 'company_write','product_read']

    description:
      groups: ['company_read', 'company_write']

    email:
      groups: ['company_read', 'company_write']

    phone:
      groups: ['company_read', 'company_write']

    address:
      groups: ['company_read', 'company_write']

    cif:
      groups: ['company_read', 'company_write']

    createdAt:
      groups: ['company_read']

    updatedAt:
      groups: ['company_read']