App\Entity\Product:
  attributes:
    id:
      groups: ['product_read']
    name:
      groups: ['product_read', 'product_write']

    description:
      groups: ['product_read', 'product_write']

    user:
      groups: ['product_read', 'product_write']

    category:
      groups: ['product_read', 'product_write']

    iva:
      groups: ['product_read', 'product_write']

    minStock:
      groups: ['product_read', 'product_write']

    maxStock:
      groups: ['product_read', 'product_write']

    stockAct:
      groups: ['product_read', 'product_write']

    company:
      groups: ['product_read', 'product_write']

    createdAt:
      groups: ['product_read']

    updatedAt:
      groups: ['product_read']