App\Entity\Product:
  attributes:
    id:
      groups: ['product_read','purchase-line_read']
    name:
      groups: ['product_read', 'product_write','purchase-line_read','purchase_read']

    description:
      groups: ['product_read', 'product_write']

    user:
      groups: ['product_read', 'product_write']

    category:
      groups: ['product_read', 'product_write']

    tax:
      groups: ['product_read', 'product_write']

    price:
      groups: ['product_read', 'product_write']

    minStock:
      groups: ['product_read', 'product_write']

    maxStock:
      groups: ['product_read', 'product_write']

    stockAct:
      groups: ['product_read', 'product_write']

    company:
      groups: ['product_read', 'product_write']

    productHeight:
      groups: ['product_read', 'product_write']

    productWidth:
      groups: ['product_read', 'product_write']

    productLength:
      groups: ['product_read', 'product_write']

    kilograms:
      groups: ['product_read', 'product_write']

    barcode:
      groups: ['product_read', 'product_write']

    reference:
      groups: ['product_read',]

    location:
      groups: ['product_read', 'product_write']

    providers:
      groups: ['product_read', 'product_write']

    createdAt:
      groups: ['product_read']

    updatedAt:
      groups: ['product_read']