App\Entity\Purchase:
  attributes:
    id:
      groups: ['purchase_read']

    reference:
      groups: ['purchase_read', 'purchase_write','purchase-line_read']

    provider:
      groups: ['purchase_read', 'purchase_write']

    total:
      groups: ['purchase_read','purchase-line_read']

    taxes:
      groups: ['purchase_read','purchase-line_read']

    final:
      groups: ['purchase_read','purchase-line_read']

    purchaseLines:
      groups: ['purchase_read']

    status:
      groups: ['purchase_read', 'purchase_write','purchase-line_read']

    company:
      groups: ['purchase_read', 'purchase_write']

    createdAt:
      groups: ['purchase_read']

    updatedAt:
      groups: ['purchase_read']