App\Entity\PurchaseLine:
  attributes:
    id:
      groups: ['purchase-line_read','purchase_read']

    company:
      groups: ['purchase-line_read', 'purchase-line_write']

    purchase:
      groups: ['purchase-line_read', 'purchase-line_write']

    product:
      groups: ['purchase-line_read', 'purchase-line_write','purchase_read']

    provider:
      groups: ['purchase-line_read', 'purchase-line_write']

    quantity:
      groups: ['purchase-line_read', 'purchase-line_write','purchase_read']

    price:
      groups: ['purchase-line_read','purchase_read']

    tax:
      groups: ['purchase-line_read','purchase_read']

    total:
      groups: ['purchase-line_read','purchase_read']

    stockAvailability:
      groups: ['purchase-line_read']

    createdAt:
      groups: ['purchase-line_read']

    updatedAt:
      groups: ['purchase-line_read']