api_platform:
  collection:
    pagination:
      page_parameter_name: _page
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'
      - '%kernel.project_dir%/config/api-platform/resources'
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
    api_keys:
      apiKey:
        name: Authorization
        type: header
  title: 'ARA system'
  description: 'ARA system multiERP'
  version: 1.0
  show_webby: false
  exception_to_status:
    \Exception: 400